### ISSUE TITLE
ical links for shows on home page

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#188]
How about this structure for each entry? 
[show name] | archive | ics

**Comment by baxgas** [comment]
ical link seems a bit awkward and hard to implement (it should be generating a downloadable file for every show)

I was thinking to generate individual/per-show google calendar links with js, since it is already checking the current date for sorting and we have everything needed on front-end. Needs some string stripping from content, conversion and formatting, here is some info:
https://stackoverflow.com/questions/44549128/link-to-add-and-save-event-in-google-calendar
https://stackoverflow.com/questions/10488831/link-to-add-to-google-calendar

Can we go this way?

**Comment by gammaw** [comment]
@baxgas I think really useful would be a **series** entry, e.g., Szmuti Csorba every Monday between 6 and 7pm. Single show entries wouldn't make too much sense, don't you think?

**Comment by gammaw** [comment]
Wasn't very easy to do. Let's leave it to our listeners :)
