### ISSUE TITLE
Schedule reload only the list not the whole homepage

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#195]
On new day the whole page reloads, but should be only the list – solve with AJAX and not whole page reload?

**Comment by baxgas** [comment]
Workaround: only reload if the player is not playing!

**Comment by gammaw** [comment]
@baxgas what is the problem again? It should only be a problem if the player is on and midnight passes and the user switches to the tab in the browser. Otherwise, if you at some point stop the player and switch to the tab the next day to re-start it, it's no problem that the whole page restarts because it does before you can hit play, no?

**Comment by baxgas** [comment]
Yes, it tracks day changes and reloads only if the player is not playing, so the Schedule is for the current day

**Comment by gammaw** [comment]
I understand. What I'm saying is that it's a rare cornercase when the player is on and there is a day change.
