### ISSUE TITLE
Enable multiple files OFF AIR Premiere

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#227]
See previous related issue: https://github.com/mmmnmnm/lahmacun/issues/65

@pvj fyi: `once` and `playlist.once` work differently: the former operates on an existing playlist, the latter creates a new playlist.

**Comment by gammaw** [comment]
Seems to work. @pvj what I can see in my first test is that files are played in the order of their upload time (oldest upload first).

**Comment by pvj** [comment]
Great! Happy to see this. I guess for now we can take care of just keeping upload order in mind when using such playlists once. I wasn't aware of that `.once` would create _new_ playlists thanks for that. I added a question to your commit otherwise LGTM

Later on, if it is still needed && when we feel ready to tackle this I guess if we want to make it more to our liking we can add some custom methods handling our playlists first? 

Finally I had time to check whether or not we have some list functions and since this is functional language it would have been weird if not, there's the `list.liq` file and the reverse function: 

https://github.com/savonet/liquidsoap/blob/master/libs/list.liq#L128

It also supports popping items one by one so we can also generate items from list and pass them to the player, until we run out of items in the playlist.

**Comment by gammaw** [comment]
@pvj we can continue this in this (https://github.com/mmmnmnm/lahmacun/issues/187) other issue, which is more general.

**Comment by gammaw** [comment]
**Important note**: no idea why but such playlist won't be shown as "Successfully loaded X tracks" in the LS logs. In fact, with log verbosity 3 there is no trace of this playlist in the log. With verbosity 5 something about the playlist is printed but the number of tracks in the playlist is not visible in the log.

**Comment by gammaw** [comment]
Changes reverted on master. It turns out that the playlist won't load changes (e.g., deletion of tracks via AC admin interface) "on the fly", i.e., LS needs to be restarted in AC for changes to take effect, which is not an acceptable use case for us. @pvj fyi

**Comment by gammaw** [comment]
One possible explanation for the add/remove tracks into/from playlist changes not taking effect is that since it's a special playlist (`playlist.once`) is the way AC contacts LS (via telnet). Maybe the command from AC to LS only works for regular playlists (well, apparently it is the case). The reason I thought of this because I see in the LS log that the playlist is reloaded upon a change, but when the playlist is supposed to start it won't find the files to play (error message in log).

**Comment by pvj** [comment]
Another possible approach might be implementing `sequence` but I don't like it it's bit dirty. 

We could possibly add index folder within folder (eg. `1` `2` `3` etc.) then use in LS something like `sequence(["/path/to/1", "/path/to/2"])` 

Hope there is neater solution just wanted to share this quickly so it's out of my thoughts for now

**Comment by gammaw** [comment]
Check what 2nd and 4th options do. Hint: see what these options generate (won't affect the custom LS config). 

![image](https://user-images.githubusercontent.com/28865986/80859708-1b8b8200-8c63-11ea-8749-6596be64c478.png)

Thanks @pvj

**Comment by gammaw** [comment]
I'll close this one as we don't have a use case for it, or at least we have a workaround (glue tracks).
