### ISSUE TITLE
Add Czitrom to background

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#307]
General background Czitrom DJ

**Comment by gammaw** [comment]
@baxgas looks good but didn't we plan to do more than just a static change? 

I think the best would be to have a solution were different background colors (lila & some nice yellow?) and pictures (lahmacun & the DJ lemon?) are loaded randomly. Does CSS support something like this? 

Btw, didn't we have this issue https://github.com/mmmnmnm/lahmacun/issues/298 for the topic? 

FYI @pvj

**Comment by gammaw** [comment]
@baxgas I talked with @pvj that we can do this static change now and do a more complex solution in the next iteration. I'll create a PR and merge it. Thanks!

**Comment by gammaw** [comment]
@baxgas just merged and pulled it on live site. Thanks again!

I realized on mobile that the main part of the background is not visible in most cases because there is a cover image in front of it. Is there a CSS setting so that the background always stays in the center even if one is scrolling down? Do you know what I mean?

**Comment by baxgas** [comment]
@gammaw Great, thanx!!!
Yes, I know this was a part of a bigger issue, but agreed with pvj to implement this ASAP.
Background is fixed, should stay always in the center of the screen, where do you have this issue on mobile?
