### ISSUE TITLE
Doesn't load player when navigate from home

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun#332]
Maybe insert player audio element in DOM, before json fetch?

**Comment by gammaw** [comment]
Seems to be no issue any more (see last mention).

**Comment by gammaw** [comment]
It's still there unfortunately. If I click "Listen" for the first time (not sure what first time really means, let's say sometimes, then the listen API answer will be shown (raw text on an empty page). Hint: as if the JS wouldn't handle the request and the plain  arcsi API will be called instead.

**Comment by gammaw** [comment]
A way I found to reproduce this bug is: 
1. Go to staging home
2. Go to MMN radio page
3. Click listen on last show -> listen API response will be returned instead of player

Hint: jQuery script doesn't seem to trigger: 

https://github.com/mmmnmnm/lahmacun/blob/e0142abf51159a428e45372a86d0e1674a1dc896/wp/wp-content/themes/lahma_maker/template-parts/content-arcsi.php#L120-L146

I will try to look into it too. 

FYI @pvj

**Comment by gammaw** [comment]
The problem seems to be that the above jQuery script is not loaded when the user navigate from home to the show subpage (because of Ajax calls probably). When the script is placed in the global scripts file, then the player seems to load fine. The first tests look good. I will look into it more thoroughly and propose commit a fix here.

**Comment by gammaw** [comment]
Background: https://api.jquery.com/load/

> jQuery uses the browser's .innerHTML property to parse the retrieved document and insert it into the current document. During this process, browsers often filter elements from the document such as <html>, <title>, or <head> elements. As a result, the elements retrieved by .load() may not be exactly the same as if the document were retrieved directly by the browser.

Script may also be filtered and not loaded with the html code.

**Comment by gammaw** [comment]
Above fix is "brute force" workaround because the arcsi player load script is only needed on show sub pages (and not on home, photos page etc.) but to load the script dynamically does not seem to be trivial. If anybody has another more elegant solution, let's go for it.
