### ISSUE TITLE
Shows backup 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun#41]
- docker cp command which is incremental (could be called via cron job)

**Comment by gammaw** [comment]
Image name: azuracast_web_v2
Path to music files: /var/azuracast/stations/boerek/media/

**Comment by gammaw** [comment]
@pvj I checked and the container name may indeed contain a hash, which may change upon Azura updates. Still, we we need to update the container name somewhere, either in the script or in the crontab entry after updates. In your solution it would be the crontab as the script is parametric. A parametric script is good for a full automated solution where the container name is automatically derived. Do we want to do it right away? 

Script: https://github.com/mmmnmnm/lahmacun/blob/archive-channel/archive_channel.sh
Crontab: https://github.com/mmmnmnm/lahmacun/commit/679d1c7c928cd9fb5009fd1dfc1be1d82d78f748

**Comment by pvj** [comment]
@gammaw Yeah, that was the original intention that we would find the container name by checking the image name (which is static) from the container list

**Comment by pvj** [comment]
There is now a version that looks at running docker containers finding the one where the parent is the `azuracast/azuracast_web_v2:latest` image (this is hardcoded -- so if they change to v3 we'll have to follow them). It gets the container id and executes the archival on that container.

**Comment by pvj** [comment]
Note if this would be related to #51 we may also check what `www`, `www_tmp`, `stations`, `stations_tmp` write out for Azuracast and then we might be able to save us a docker cp command and just move files on the host filesystem.

**Comment by gammaw** [comment]
@pvj crontab sends email on every execution, right?

**Comment by gammaw** [comment]
@pvj I see no delete in the script. Archive dir should be emptied before copying.

**Comment by gammaw** [comment]
@pvj if we want to do backup ourselves an option is the "duply" package (wrapping "duplicity") which can write backups onto an external storage (e.g., Amazon S3 bucket)

**Comment by pvj** [comment]
A new version of the archive channel script is running now -- 

Since both the azuracast and our own custom containers mount volumes we can leverage that and instead of copying things out from the running container w/ `docker cp` we are just using `cp` to copy data within the host filesystem.  

Partly because of this, the script now works simpler. Just specify the path as the only argument of the folder you want to copy. The script will check if there is an argument, if the argument is a path to a folder, and will create if necessary the destination archive folder. If all is correct, it will then do the copying around. 

These are all running once a week (Monday 1 am to 5 am) with a crontab that is kept out of version control since it contains sensitive data. F.e. I've added the mysqldump also on a line of its own, so having any of the users, passes, db names would be unfortunate.

**Comment by gammaw** [comment]
@pvj azura version 0.9.5.1 comes with built-on backup :) still, backuping wordpress needs to be done by us. plus, the azura feature needs to be tested.

**Comment by gammaw** [comment]
@pvj fyi: https://github.com/AzuraCast/AzuraCast/issues/1637#issuecomment-502469452

**Comment by gammaw** [comment]
Automatic backup appears to work somehow. But where is today's backup? 

![image](https://user-images.githubusercontent.com/28865986/59974855-2d1aec80-95b1-11e9-94da-d07ac88877af.png)

@pvj we should check if we can really restore a backup. For example, we can delete a couple of things, do the restore and check if deleted things reappeared.

**Comment by gammaw** [comment]
Hint: use `crontab -e` to change the cron file and don't directly edit it otherwise the cron service will use the old cron file.
